# Exam

## 1. Numpy basics

### Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles. The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448.

- Construct a 2D grid of distances among each city along Route 66
- Convert that in km (those savages...)

In [4]:
import numpy as np
distances = [0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448]

# 2D grid of distances.
grid_dist = np.array([[abs(i - j) for j in distances] for i in distances ])

# In km.
grid_dist_km = 1.61*grid_dist

print('Grid distances in miles:','\n','\n',grid_dist,'\n','\n','Grid distances in kilometers:','\n','\n',grid_dist_km)

Grid distances in miles: 
 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]] 
 
 Grid distances in kilometers: 
 
 [[   0.    318.78  487.83 1184.96 1402.31 1891.75 2374.75 2485.84 3079.93
  3941.28]
 [ 318.78    0.    169.05  866.18 1083.53 1572.97 2055.97 2167.06 2761.15
  3622.5 ]
 [ 487.83  169.05    0.    697.13  914.48 1403.92 1886.92 1998.01 2592.1
  3453.45]
 [1184.96  866.18  697.13    0.    217.35  706.79 1189.79 1300.88 1894.97
  2756.32]
 [1402.31 1083.53  914.48  217.35    0.    489.44  972.44 1083.

## 2. Bash

The following tasks needs to be implemented in a script. They script needs first to be tested by running it on a terminal; the script's content must then be copied in the cell below

* Make a new directory called `students` in your home. Download a csv file with the list of students of this lab from [here](https://www.dropbox.com/s/867rtx3az6e9gm8/LCP_22-23_students.csv) (use the `wget` command) and copy that to `students`. First implement a bash command to check whether the file is already there
* Make two new files, one containing the students belonging to PoD, the other to Physics.
* For each letter of the alphabet, count the number of students whose surname starts with that letter. 
* Find out which is the letter with most counts.
* Assume an obvious numbering of the students in the file (first line is 1, second line is 2, etc.), group students "modulo 18", i.e. 1,19,37,.. 2,20,38,.. etc. and put each group in a separate file


In [1]:
### here goes the bash code 

#!/bin/bash

mkdir students

if [ ! "LCP_22-23_students.csv" ] wget "https://www.dropbox.com/scl/fi/bxv17nrbrl83vw6qrkiu9/LCP_22-23_students.csv?rlkey=47fakvatrtif3q3qw4q97p5b7&e=1" -O "LCP_22-23_students.csv"; else echo "File already exists."; fi

grep "PoD" LCP_22-23_students.csv > PoD
grep "Physics" LCP_22-23_students.csv > PoD


for L in {A..Z}; echo "$L :"; cut -d "," -f1 LCP_22-23_students.csv | grep -c "^$L";done

Letter=""
max=0
for L in {A..Z};
c = ( cut -d "," -f1 LCP_22-23_students.csv | grep -c "^$L");
if [$c -gt $max] $max = $c;
$Letter=$L;
fi;
done

for i in $( seq 2 $(wc -l < LCP_22-23_students.csv));g=( (i-2)%18+1 ); sed -n {"$i"p} >> Group_$g;done

SyntaxError: invalid syntax (<ipython-input-1-53a39252df6d>, line 2)

## 3. Pandas

This exercise consists in analyzing a dataset containg timing information from a series of Time-to-Digital-Converters (TDC) implemented in a couple of FPGAs. Each measurement (i.e. each row of the input file) consists of a flag that specifies the type of message ('HEAD', which in this case is always 1), two addresses of the TDC providing the signal ('FPGA' and 'TDC_CHANNEL'), and the timing information ('ORBIT_CNT', 'BX_COUNTER', and 'TDC_MEAS'). Each TDC count corresponds to 25/30 ns, whereas a unit of BX_COUNTER corresponds to 25 ns, and the ORBIT_CNT is increased every 'x' BX_COUNTER. This allows to store the time in a similar way to hours, minutes and seconds.

- Download the relevant file
```
!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt -P ~/data/
```

- Create a Pandas DataFrame reading N rows of the 'data_000637.txt' dataset. Choose N to be smaller than or equal to the maximum number of rows and larger that 10k.

- Find out the number of BX in a ORBIT (the value 'x').

- Find out how much the data taking lasted. You can either make an estimate based on the fraction of the measurements (rows) you read, or perform this check precisely by reading out the whole dataset.

- Create a new column with the absolute time in ns (as a combination of the other three columns with timing information).

- Replace the values (all 1) of the HEAD column randomly with 0 or 1.

- Create a new DataFrame that contains only the rows with HEAD=1.

- Make two occupancy plots (one for each FPGA), i.e. plot the number of counts per TDC channel

- Use the groupby method to find out the noisy channels, i.e. the TDC channels with most counts (say the top 3)

- Count the number of unique orbits. Count the number of unique orbits with at least one measurement from TDC_CHANNEL=139

In [1]:
# Download the relevant file.
import pandas as pd
file = pd.read_csv("/Users/itter/UNIPD 1st year programming/LaboratoryOfComputationalPhysics_Y8/data/data_000637.txt")
pd = pd.DataFrame(file)

# Pandas DataFrame reading N rows of the 'data_000637.txt' dataset. 
# Choose N to be smaller than or equal to the maximum number of rows and larger that 10k.
def pd2(N):
    if N>1e4 and N <= len(pd):
        return pd[:N]
    else:
        return print("N has to be  smaller than or equal to the maximum number of rows and larger that 10k.")

# Number of BX in a ORBIT.
A = pd.groupby(['ORBIT_CNT'])['BX_COUNTER'].max()
x = A.max() + 1 # As in the next step it's 0 again.
print("Number of BX in a ORBIT:",x,'\n')

# Find out how much the data taking lasted.
TDC_time = 25/30 * 1e-9
BX_time = 25 * 1e-9
Time = []
Orbits = pd["ORBIT_CNT"].max() - pd["ORBIT_CNT"].min() 
Bxs = pd["BX_COUNTER"].max() - pd["BX_COUNTER"].min() # In fact this is wrong as it's included in orbits
Tdcs = pd["TDC_MEAS"].max() - pd["TDC_MEAS"].min() 
Time = Orbits * x * BX_time   + Tdcs * TDC_time
print('Data lasted:', Time,'seconds')

# Replace the values (all 1) of the HEAD column randomly with 0 or 1.
pd["HEAD"] = np.random.randint(0,2,len(pd))

# Create a new DataFrame that contains only the rows with HEAD=1.
pd3 = pd[ pd["HEAD"]==1 ]

# Make two occupancy plots (one for each FPGA), i.e. plot the number of counts per TDC channel.

# Count the number of unique orbits. Count the number of unique orbits with at least one measurement from TDC_CHANNEL=139.
n = pd["ORBIT_CNT"].unique().item()
print('\n','Number of unique orbits:',n)



Number of BX in a ORBIT: 3564 

Data lasted: 0.9804564241666668 seconds


NameError: name 'np' is not defined

In [12]:
pd["time_s"] = (
    pd["ORBIT_CNT"] * x * BX_time # This way we pass orbits to bx counts so we can pass them to seconds.
    + pd["BX_COUNTER"] * BX_time
    + pd["TDC_MEAS"] * TDC_time
)
pd

,HEAD,FPGA,TDC_CHANNEL,ORBIT_CNT,BX_COUNTER,TDC_MEAS,time_s
0,0,0,123,3869200167,2374,26,344745.734939
1,1,0,124,3869200167,2374,27,344745.734939
2,1,0,63,3869200167,2553,28,344745.734944
3,0,0,64,3869200167,2558,19,344745.734944
4,0,0,64,3869200167,2760,25,344745.734949
...,...,...,...,...,...,...,...
1310715,0,0,62,3869211171,762,14,344746.715355
1310716,0,1,4,3869211171,763,11,344746.715355
1310717,1,0,64,3869211171,764,0,344746.715355
1310718,1,0,139,3869211171,769,0,344746.715355


## 4. Monte Carlo

### Monte Carlo integration: hit/miss vs mean value method

Consider the function
$$
f(x) =\sin^2\frac{1}{x(2-x)}
$$

- Compute the integral of $f(x)$ between 0 and 2 with the hit/miss method. Evaluate the error of your estimate.
- Repeat the integral with the mean value method. Evaluate the error and compare it with the previous one.

In [143]:
import numpy as np
Area = 2
x = np.linspace(0,2,1000)
y = np.linspace(0,1,1000)

def f(x):
    return np.sin(1 / (x*(2-x)))**2
Z = zip(x,y)
hit = Z[y<f(x)]
#integral = 

#I = 1/2 * 
    